server:
  port: 8585

spring:
  datasource: 
    url: jdbc:mysql://localhost:3306/flo_db
    username: root
    password: 1234
  thymeleaf:
    enabled: true
    cache: false
    prefix: classpath:/templates/views/
    suffix: .html
  servlet: 
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 110MB
flo:
  file:
    adminImg: /home/flo/admin/img
    musicfiles: /home/flo/music/files
    userImg: /home/flo/user/img
    albumImg: /home/flo/album/img