server:
  port: 8585

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flo_db
    username: root
    password: 1234
  thymeleaf:
    enabled: true
    cache: false
    prefix: classpath:/templates/views/
    suffix: .html
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 110MB
flo:
  file:
    adminImg: /home/flo/admin/img
    musicfiles: /home/flo/music/files
    userImg: /home/flo/user/img
    albumImg: /home/flo/album/img

# Swagger Settings 
springdoc:
  # 요청 데이터 형태
  default-consumes-media-type: application/json
  # 응답 데이터 형태
  default-produces-media-type: application/json
  api-docs:
    groups:
      # API 문서 그룹화 여부
      enabled: true
  swagger-ui:
    # 정렬 기준(알파벳 기준)
    operations-sorter: alpha
    tags-sorter: alpha
    # swagger 접근 기본 경로
    path: /swagger
    # 기본 경로 설정 비활성화 여부 
    disable-swagger-default-url: true
    # 문서 확장기능 사용 여부 
    doc-expansion: none
  paths-to-match:
    # 문서로 만들 API 요청 경로 목록 ( 요청 경로가 /api/로 시작하면 모두 문서화) 
    - /api/**